version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/aula2_mlop_infra/docker/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/aula3_case_study/docker/"
    schedule:
      interval: "weekly"
